AWSTemplateFormatVersion: 2010-09-09
Description: ---
Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: 
        www.komabagorilla.com
      WebsiteConfiguration: 
        IndexDocument: index.html
  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3Bucket
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource:
              - !GetAtt s3Bucket.Arn
              - !Join [ "/", [ !GetAtt s3Bucket.Arn, "*" ] ] 
            Principal: '*'
