name: S3 Deploy
on:
  push:
      branches:
        - main
  workflow_dispatch:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master  # リポジトリをチェックアウト

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          aws s3 cp --region ap-northeast-1 ./index.html s3://komabagorilla.com/;
          aws s3 cp --recursive --region ap-northeast-1 ./css s3://komabagorilla.com/css/;
          aws s3 cp --recursive --region ap-northeast-1 ./js s3://komabagorilla.com/js/;
          aws s3 cp --recursive --region ap-northeast-1 ./assets s3://komabagorilla.com/assets/;
          aws cloudfront create-invalidation --distribution-id E35OGRQKOW5NXU --paths "/*"
